### ISSUE TITLE
Harmonic sampling

### ISSUE THREAD

**Issue by danielhollas** [PHOTOX/photoxrepo#3]
1) We should crosscheck the harmonic wigner sampling in MOLPRO with other programs, ideally NEWTON-X.

2) We could also make scripts for wigner transform with development version of terachem.

3) We should make scripts to convert frequencies output from other programs, e.g. Gaussian or ORCA. (both have analytical frequencies)
Currently, there is only script mp2freq for MOLPRO, which only has numerical frequencies.

**Comment by suchanj** [comment]
I just uploaded script (MISC/wignerSHARC.sh) which is using the SHARC wigner sampling utility. I crosschecked it with current script, there are no deviations.

**Comment by danielhollas** [comment]
@suchanj nice! So then we can probably consider this solved? Maybe I would move the FMS-Wigner scripts to the OLD folder? I'd assume that the new script is nicer to use...

**Comment by suchanj** [comment]
@danielhollas Allright, the new script is much faster, easy to use. HARMONIC-SAMPLING moved to OLD, closing the issue.
